name: Stork Upload Artifact
description: Uploads an artifact to Stork platform
author: Erick Zanardo
branding:
  icon: loader
  color: purple

inputs:
  version:
    description: 'The version where the artifact will be uploaded'
    required: true
  stork-url:
    description: 'The URL of the Stork API'
    default: 'https://stork.erickzanardoo.workers.dev'
  app-id:
    description: 'The ID of the app'
    required: true
  api-key:
    description: 'The API key to authenticate with the Stork API'
    required: true
  platform:
    description: 'The platform of the artifact'
    required: true
  artifact-path:
    description: 'The path to the artifact'
    required: true
  fileName:
    description: 'The file name of the artifact'
    required: false

runs:
  using: composite
  steps:
    - name: Upload Artifact
      shell: bash
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ inputs.api-key }}" \
          --data-binary @${{ inputs.artifact-path }} \
          ${{ inputs.stork-url }}/v1/admin/apps/${{ inputs.app-id }}/versions/${{ inputs.version }}/artifacts/platforms/${{ inputs.platform }}
    - name: Set artifact file name
      if: ${{ inputs.fileName }}
      shell: bash
      run: |
        curl -X PATCH \
          -H "Authorization: Bearer ${{ inputs.api-key }}" \
          -H "Content-Type: application/json" \
          -d "{\"fileName\": \"${{ inputs.fileName }}\"}" \
          ${{ inputs.stork-url }}/v1/admin/apps/${{ inputs.app-id }}/versions/${{ inputs.version }}/artifacts/platforms/${{ inputs.platform }}
